(() => {
'use strict';
const E=globalThis.EasyFa=globalThis.EasyFa||{};
const touched=new Map();
let state=null,pid=null,current=null,currentFace=null,observer=null,queued=false,epoch=0,inputBound=false,stableStyle=null,lastUrl=location.href,urlTimer=null;
const VARS=['--easyfa-font-family','--easyfa-font-size','--easyfa-font-weight','--easyfa-line-height'];
const FONT_NODES='span,p,strong,b,em,i,u,s,blockquote';
const STABLE_FALLBACK='system-ui,-apple-system,"Segoe UI",Tahoma,Arial,sans-serif';
function profile(){return current}
function remember(el){let s=touched.get(el);if(s)return s;const cs=getComputedStyle(el);s={dir:el.getAttribute('dir'),easyDir:null,font:cs.fontFamily||STABLE_FALLBACK};touched.set(el,s);return s}
function setVar(el,k,v){if(v==null)el.style.removeProperty(k);else el.style.setProperty(k,v)}
function restore(el){const s=touched.get(el);if(!s)return;VARS.forEach(k=>el.style.removeProperty(k));if(s.easyDir&&el.getAttribute('dir')===s.easyDir){if(s.dir==null)el.removeAttribute('dir');else el.setAttribute('dir',s.dir)}delete el.dataset.easyfaMessage;delete el.dataset.easyfaComposer;delete el.dataset.easyfaFontNode;delete el.dataset.easyfaSidebar;delete el.dataset.easyfaDir;touched.delete(el)}
function removeStable(){stableStyle?.remove();stableStyle=null;document.documentElement?.removeAttribute('data-easyfa-platform')}
function clear(){removeStable();for(const el of [...touched.keys()])el.isConnected?restore(el):touched.delete(el)}
function text(el){return String(el?.innerText||el?.textContent||'').trim()}
function direction(el,mode){const s=touched.get(el);delete el.dataset.easyfaDir;if(mode==='site'){if(s?.easyDir&&el.getAttribute('dir')===s.easyDir){if(s.dir==null)el.removeAttribute('dir');else el.setAttribute('dir',s.dir)}if(s)s.easyDir=null;return}if(mode==='smart'){el.setAttribute('dir','auto');if(s)s.easyDir='auto';el.dataset.easyfaDir='smart';return}const d=mode==='ltr'?'ltr':'rtl';el.setAttribute('dir',d);if(s)s.easyDir=d;el.dataset.easyfaDir=d}
function applyTypography(el,p,ff){const s=remember(el),family=p.fontScope==='all'?ff.family:ff.faFamily;setVar(el,'--easyfa-font-family',`${family}, ${s.font||STABLE_FALLBACK}`);if(p.sizeScope==='all'){setVar(el,'--easyfa-font-size',`${p.fontSize}px`);setVar(el,'--easyfa-font-weight',String(p.fontWeight));setVar(el,'--easyfa-line-height',String(p.lineHeight))}else{setVar(el,'--easyfa-font-size',null);setVar(el,'--easyfa-font-weight',null);setVar(el,'--easyfa-line-height',null)}}
function forceTelegramChildren(el,p,ff){if(pid!=='telegram')return;for(const n of el.querySelectorAll(FONT_NODES)){if(!n.isConnected||E.Detector.protectedEl(n,pid)||n.closest('[data-easyfa-composer="1"]'))continue;applyTypography(n,p,ff);n.dataset.easyfaFontNode='1'}}
async function apply(el,p,kind,token){if(!el?.isConnected)return;if(kind!=='sidebar'&&E.Detector.protectedEl(el,pid))return;if(!text(el)&&kind!=='composer')return;let ff=currentFace;if(!ff){try{ff=await E.FontLoader.faceFor(p)}catch{return}}if(token!==epoch||!el.isConnected)return;applyTypography(el,p,ff);if(kind==='composer')el.dataset.easyfaComposer='1';else if(kind==='sidebar')el.dataset.easyfaSidebar='1';else el.dataset.easyfaMessage='1';if(kind==='message')forceTelegramChildren(el,p,ff);direction(el,p.direction)}
function stableCss(p,ff){const selectors=E.Detector.selectors(pid,p);if(!selectors.length)return'';const family=p.fontScope==='all'?ff.family:ff.faFamily,props=[`font-family:${family},${STABLE_FALLBACK}!important`,'font-synthesis:none'];if(p.sizeScope==='all')props.push(`font-size:${p.fontSize}px!important`,`font-weight:${p.fontWeight}!important`,`line-height:${p.lineHeight}!important`);return selectors.map(s=>`${s}{${props.join(';')}}`).join('\n')}
function installStable(p,ff){removeStable();if(!p?.enabled||!ff||!document.documentElement)return;const css=stableCss(p,ff);if(!css)return;stableStyle=document.createElement('style');stableStyle.id='easyfa-stable-style';stableStyle.textContent=css;(document.head||document.documentElement).appendChild(stableStyle);document.documentElement.dataset.easyfaPlatform=pid||'custom'}
async function scan(){queued=false;const p=profile();if(!p)return;if(!p.enabled){clear();return}const r=E.Detector.root(pid);if(!r)return;const token=epoch,messages=E.Detector.messages(r,pid);await Promise.allSettled(messages.map(el=>apply(el,p,'message',token)));if(p.composer){const composers=E.Detector.composers(document,pid);await Promise.allSettled(composers.map(el=>apply(el,p,'composer',token)))}if(p.sidebar){const sidebars=E.Detector.sidebars(pid);await Promise.allSettled(sidebars.map(el=>apply(el,p,'sidebar',token)))}for(const el of [...touched.keys()])if(!el.isConnected)touched.delete(el)}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{scan().catch(()=>{queued=false})})}
function watch(){observer?.disconnect();observer=new MutationObserver(ms=>{for(const m of ms){if(m.type==='childList'||m.type==='characterData'||m.type==='attributes'){schedule();break}}});observer.observe(document.documentElement||document,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','role','data-message-author-role','data-testid']});if(!inputBound){document.addEventListener('input',e=>{if(profile()?.composer&&e.target?.closest?.('[contenteditable="true"],textarea,input'))schedule()},true);inputBound=true}if(!urlTimer){urlTimer=setInterval(()=>{if(location.href!==lastUrl){lastUrl=location.href;schedule()}},700)}}
async function reload(){const token=++epoch;clear();state=await E.Storage.load();pid=E.Detector.platform();current=pid==='custom'?(E.Storage.matchCustom(state)?.profile||null):(state.profiles?.[pid]||null);currentFace=null;if(token!==epoch||!current)return;if(!current.enabled){clear();return}try{currentFace=await E.FontLoader.faceFor(current)}catch{currentFace=null}if(token!==epoch)return;await scan();if(token!==epoch)return;if(currentFace)installStable(current,currentFace);schedule()}
chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&c[E.Config.KEY])reload()});addEventListener('pageshow',schedule);addEventListener('popstate',schedule);addEventListener('hashchange',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});document.fonts?.ready?.then?.(schedule).catch?.(()=>{});reload().then(watch);
})();
