(() => {
'use strict';
const E=globalThis.EasyFa=globalThis.EasyFa||{};
const touched=new Map();let state=null,pid=null,current=null,observer=null,queued=false,epoch=0,inputBound=false;
function profile(){return current}
function remember(el){if(!touched.has(el))touched.set(el,{style:el.getAttribute('style'),dir:el.getAttribute('dir')})}
function restore(el){const s=touched.get(el);if(!s)return;if(s.style==null)el.removeAttribute('style');else el.setAttribute('style',s.style);if(s.dir==null)el.removeAttribute('dir');else el.setAttribute('dir',s.dir);delete el.dataset.easyfaMessage;delete el.dataset.easyfaComposer;touched.delete(el)}
function clear(){for(const el of [...touched.keys()])el.isConnected?restore(el):touched.delete(el)}
function text(el){return String(el?.innerText||el?.textContent||'').trim()}
function direction(el,mode){el.style.setProperty('unicode-bidi','plaintext','important');if(mode==='site'){el.removeAttribute('dir');el.style.removeProperty('direction');el.style.removeProperty('text-align');return}if(mode==='smart'){el.setAttribute('dir','auto');el.style.removeProperty('direction');el.style.setProperty('text-align','start','important');return}const d=mode==='ltr'?'ltr':'rtl';el.setAttribute('dir',d);el.style.setProperty('direction',d,'important');el.style.setProperty('text-align',d==='rtl'?'right':'left','important')}
async function apply(el,p,composer,token){if(!el?.isConnected||E.Detector.protectedEl(el,pid))return;if(!text(el)&&!composer)return;remember(el);const cs=getComputedStyle(el),original=cs.fontFamily||'system-ui,sans-serif',basePx=parseFloat(cs.fontSize)||16;let ff;try{ff=await E.FontLoader.faceFor(p,basePx)}catch{return}if(token!==epoch||!el.isConnected)return;el.dataset[composer?'easyfaComposer':'easyfaMessage']='1';const family=p.fontScope==='all'?ff.family:ff.faFamily;el.style.setProperty('font-family',`${family}, ${original}`,'important');if(p.sizeScope==='all'){el.style.setProperty('font-size',`${p.fontSize}px`,'important');el.style.setProperty('font-weight',String(p.fontWeight),'important');el.style.setProperty('line-height',String(p.lineHeight),'important')}else{el.style.removeProperty('font-size');el.style.removeProperty('font-weight');el.style.removeProperty('line-height')}direction(el,p.direction)}
async function scan(){queued=false;const p=profile();if(!p)return;if(!p.enabled){clear();return}const r=E.Detector.root(pid);if(!r)return;const token=epoch,list=E.Detector.messages(r,pid);await Promise.allSettled(list.map(el=>apply(el,p,false,token)));if(p.composer)await Promise.allSettled(E.Detector.composers(r,pid).map(el=>apply(el,p,true,token)))}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(scan)}
function watch(){observer?.disconnect();observer=new MutationObserver(ms=>{for(const m of ms){if(m.type==='childList'||m.type==='characterData'){schedule();break}}});observer.observe(document.documentElement||document,{subtree:true,childList:true,characterData:true});if(!inputBound){document.addEventListener('input',e=>{if(profile()?.composer&&e.target?.closest?.('[contenteditable="true"],textarea,input'))schedule()},true);inputBound=true}}
async function reload(){epoch++;clear();state=await E.Storage.load();pid=E.Detector.platform();if(pid==='custom'){const x=E.Storage.matchCustom(state);current=x?.profile||null}else current=state.profiles?.[pid]||null;if(!current)return;schedule()}
chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&c[E.Config.KEY])reload()});addEventListener('pageshow',schedule);addEventListener('popstate',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});reload().then(watch);
})();
