(() => {'use strict';
const E=globalThis.EasyFa=globalThis.EasyFa||{};
const host=()=>location.hostname.replace(/^www\./,'').toLowerCase();
const platform=()=>{
  const h=host();
  if(h==='kick.com')return'kick';
  if(h.endsWith('youtube.com')){
    if(location.pathname.startsWith('/live_chat')||document.querySelector('yt-live-chat-renderer,yt-live-chat-item-list-renderer'))return'youtubeLive';
    return'youtube';
  }
  if(h==='twitch.tv')return'twitch';
  if(h==='web.whatsapp.com')return'whatsapp';
  if(h==='web.telegram.org')return'telegram';
  if(h==='discord.com')return'discord';
  if(h==='mail.google.com')return'gmail';
  if(h==='chatgpt.com'||h==='chat.openai.com')return'chatgpt';
  if(h==='gemini.google.com')return'gemini';
  return'custom'
};
const D={
  kick:{roots:['#channel-chatroom','[data-testid="chatroom-messages"]','#chatroom-messages','[data-testid="chatroom"]','main','body'],messages:['[data-testid="chat-message-content"]','[data-chat-message-content]'],protect:['[data-testid*="username" i]','[data-username]','[data-testid*="badge" i]','time','button','a'],compose:['textarea[placeholder*="chat" i]','[contenteditable="true"][role="textbox"]']},
  youtube:{roots:['ytd-app','ytd-watch-flexy','#primary','main','body'],messages:['.ytp-caption-segment','.ytp-caption-window-container .ytp-caption-segment','ytd-watch-metadata #title h1 yt-formatted-string','h1.ytd-watch-metadata yt-formatted-string','ytd-video-primary-info-renderer h1.title yt-formatted-string','#title h1 yt-formatted-string'],protect:['#channel-name','#owner','#upload-info','a','button','time','yt-icon'],compose:[]},
  youtubeLive:{roots:['yt-live-chat-renderer','yt-live-chat-item-list-renderer','#items.yt-live-chat-item-list-renderer','body'],messages:['yt-live-chat-text-message-renderer #message','yt-live-chat-paid-message-renderer #message','yt-live-chat-membership-item-renderer #message'],protect:['#author-name','#timestamp','#author-badges','yt-live-chat-author-badge-renderer','a'],compose:['#input[contenteditable="true"]','yt-live-chat-text-input-field-renderer #input','yt-live-chat-text-input-field-renderer [contenteditable="true"]','[contenteditable="true"][role="textbox"]']},
  twitch:{roots:['[data-a-target="chat-room-component-layout"]','.chat-scrollable-area__message-container','[role="log"]','main','body'],messages:['[data-a-target="chat-message-text"]','[data-test-selector="chat-message-text"]'],fragments:['.text-fragment'],protect:['[data-a-target="chat-message-username"]','[data-test-selector="message-username"]','[data-a-target*="badge" i]','time','a'],compose:['[data-a-target="chat-input"]','textarea[data-a-target*="chat" i]']},
  whatsapp:{roots:['#main','[data-testid="conversation-panel-wrapper"]','main','body'],messages:['[data-testid="msg-container"] span.selectable-text','[data-testid="msg-container"] [data-lexical-text="true"]','[data-testid="msg-container"] [data-testid="msg-text"]','.message-in span.selectable-text','.message-out span.selectable-text'],protect:['[data-pre-plain-text]','time','a','button'],compose:['[data-testid="conversation-compose-box-input"]','footer [contenteditable="true"][role="textbox"]','footer [contenteditable="true"][data-lexical-editor="true"]','footer [contenteditable="true"]','[contenteditable="true"][role="textbox"]']},
  telegram:{roots:['#column-center','.MiddleColumn','.MessageList','.bubbles-inner','.messages-container','.chat-container','.chat','main','body'],messages:['.bubble:not(.service):not(.is-date) .message','.bubble:not(.service):not(.is-date) .text-content','.bubble:not(.service):not(.is-date) .translatable-message','.bubble:not(.service):not(.is-date) .media-caption','.MessageList .Message:not(.ActionMessage) .text-content','.MessageList .Message:not(.ActionMessage) .message-text','.MessageList .Message:not(.ActionMessage) .media-caption','.Message:not(.ActionMessage) .text-content','.message-content','.translatable-message','[class*="message-content"] [class*="text-content"]'],sidebars:['.chatlist .ListItem .title','.chatlist .ListItem .subtitle','.ChatList .ListItem .title','.ChatList .ListItem .subtitle','.LeftColumn .ListItem .title','.LeftColumn .ListItem .subtitle','.LeftColumn .peer-title','[class*="chatlist"] [class*="peer-title"]','[class*="ChatList"] [class*="peer-title"]','[class*="chatlist"] [class*="title"]','[class*="ChatList"] [class*="title"]'],protect:['.peer-title','.sender-title','.message-title','.message-time','.time','.date','.avatar','.reactions','.reaction','.reply-title','.forwarded-title','time','a','button','[role="button"]'],compose:['.input-message-input[contenteditable="true"]','.input-message-input[contenteditable]','#editable-message-text[contenteditable="true"]','#editable-message-text[contenteditable]','.composer [contenteditable="true"]','.input-field-input[contenteditable="true"]','[contenteditable="true"][role="textbox"]']},
  discord:{roots:['[data-list-id="chat-messages"]','ol[data-list-id="chat-messages"]','main[aria-label]','main','body'],messages:['[id^="message-content-"]'],protect:['[id^="message-username-"]','[id^="message-timestamp-"]','[class*="username"]','time','a','button'],compose:['[role="textbox"][data-slate-editor="true"]','[data-slate-editor="true"][contenteditable="true"]','div[role="textbox"][contenteditable="true"]']},
  gmail:{roots:['div[role="main"]','main','body'],messages:['.a3s'],protect:['span[email]','[email]','time','a','button'],compose:['div[aria-label="Message Body"]','div[role="textbox"][contenteditable="true"]']},
  chatgpt:{roots:['main','[role="main"]','body'],messages:['[data-message-author-role="assistant"] .markdown','[data-message-author-role="assistant"] [class*="whitespace-pre-wrap"]','[data-message-author-role="user"] [class*="whitespace-pre-wrap"]','[data-testid^="conversation-turn-"] .markdown','[data-testid^="conversation-turn-"] [class*="whitespace-pre-wrap"]'],sidebars:['nav a[href^="/c/"]','aside a[href^="/c/"]','nav [data-testid*="history" i] a','nav [data-testid*="conversation" i]','[data-testid*="sidebar" i] a[href^="/c/"]'],protect:['pre','code','kbd','samp','button','textarea','input','[contenteditable="true"]','svg'],compose:['#prompt-textarea','textarea[placeholder]','[contenteditable="true"][role="textbox"]']},
  gemini:{roots:['main','chat-window','[role="main"]','body'],messages:['.model-response-text','message-content','.message-content','[data-test-id="model-response"]','[data-test-id="user-query"]','.query-text','user-query'],sidebars:['side-navigation a','nav a[href*="/app/"]','[class*="conversation"] a','[class*="history"] a'],protect:['pre','code','kbd','samp','button','textarea','input','[contenteditable="true"]','svg'],compose:['rich-textarea [contenteditable="true"]','textarea','[contenteditable="true"][role="textbox"]']},
  custom:{roots:['main','[role="main"]','body'],messages:[],protect:['nav','header','footer','button','a','time','[role="button"]','[contenteditable="true"]','input','textarea','pre','code'],compose:['textarea','[contenteditable="true"][role="textbox"]']}
};
const qs=(r,s)=>{try{return [...r.querySelectorAll(s)]}catch{return[]}};
const many=(r,a)=>{const z=new Set;for(const s of a||[])qs(r,s).forEach(n=>z.add(n));return[...z]};
function root(p){for(const s of D[p]?.roots||[]){const n=document.querySelector(s);if(n)return n}return document.body||document.documentElement}
function protectedEl(el,p){return(D[p]?.protect||[]).some(s=>{try{return!!el.closest(s)}catch{return false}})}
function explicitMessages(r,p){const set=new Set(many(r,D[p]?.messages));if(p==='twitch'&&!set.size){for(const f of many(r,D[p]?.fragments)){const el=f.closest('[data-a-target="chat-line-message"]')?f.parentElement:f;if(el&&!protectedEl(el,p))set.add(el)}}return[...set].filter(x=>x&&x!==r&&!protectedEl(x,p))}
function fallbackMessages(r,p){const out=new Set(),AR=/[\u0600-\u06FF\u0750-\u077F\u0870-\u089F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/;const w=document.createTreeWalker(r,NodeFilter.SHOW_TEXT,{acceptNode(n){const t=(n.nodeValue||'').trim();if(!t||!AR.test(t))return NodeFilter.FILTER_REJECT;const e=n.parentElement;if(!e||e===r||protectedEl(e,p)||e.closest('script,style,button,[role="button"],input,textarea,pre,code')||e.isContentEditable)return NodeFilter.FILTER_REJECT;const meta=`${e.id||''} ${typeof e.className==='string'?e.className:''} ${e.getAttribute?.('data-testid')||''} ${e.getAttribute?.('aria-label')||''}`;if(/user(name)?|author|sender|badge|timestamp|avatar|reaction|status|menu|tooltip|\btime\b/i.test(meta))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});let n,count=0;while((n=w.nextNode())&&count<900){let el=n.parentElement;if(!el)continue;while(el.parentElement&&el.parentElement!==r&&el.parentElement.childElementCount<=1&&!protectedEl(el.parentElement,p)&&!el.parentElement.matches('li,[role="listitem"],pre,code'))el=el.parentElement;if(el!==r){out.add(el);count++}}return[...out]}
function messages(r,p){const found=explicitMessages(r,p);if(p==='telegram'||p==='chatgpt'||p==='gemini'){const all=new Set(found);fallbackMessages(r,p).forEach(x=>all.add(x));return[...all]}return found.length?found:fallbackMessages(r,p)}
function sidebars(p){return many(document,D[p]?.sidebars)}
function selectors(p,profile){const d=D[p]||{},out=[...(d.messages||[])];if(profile?.composer)out.push(...(d.compose||[]));if(profile?.sidebar)out.push(...(d.sidebars||[]));return[...new Set(out)]}
E.Detector={platform,defs:D,root,messages,sidebars,selectors,protectedEl,composers:(r,p)=>many(r,D[p]?.compose).filter(x=>!protectedEl(x,p))};
})();
