(() => {'use strict';
const E=globalThis.EasyFa=globalThis.EasyFa||{};
const host=()=>location.hostname.replace(/^www\./,'').toLowerCase();
const platform=()=>{const h=host();if(h==='kick.com')return'kick';if(h.endsWith('youtube.com'))return'youtube';if(h==='twitch.tv')return'twitch';if(h==='web.whatsapp.com')return'whatsapp';if(h==='web.telegram.org')return'telegram';if(h==='discord.com')return'discord';if(h==='mail.google.com')return'gmail';return'custom'};
const D={
 kick:{roots:['#channel-chatroom','[data-testid="chatroom-messages"]','#chatroom-messages','[data-testid="chatroom"]'],messages:['[data-testid="chat-message-content"]','[data-chat-message-content]'],protect:['[data-testid*="username" i]','[data-username]','[data-testid*="badge" i]','time','button','a'],compose:['textarea[placeholder*="chat" i]','[contenteditable="true"][role="textbox"]']},
 youtube:{roots:['yt-live-chat-renderer','yt-live-chat-item-list-renderer','#items.yt-live-chat-item-list-renderer'],messages:['yt-live-chat-text-message-renderer #message','yt-live-chat-paid-message-renderer #message','yt-live-chat-membership-item-renderer #message'],protect:['#author-name','#timestamp','#author-badges','yt-live-chat-author-badge-renderer','a'],compose:['#input[contenteditable="true"]','yt-live-chat-text-input-field-renderer [contenteditable="true"]']},
 twitch:{roots:['[data-a-target="chat-room-component-layout"]','.chat-scrollable-area__message-container','[role="log"]'],messages:['[data-a-target="chat-message-text"]','[data-test-selector="chat-message-text"]'],fragments:['.text-fragment'],protect:['[data-a-target="chat-message-username"]','[data-test-selector="message-username"]','[data-a-target*="badge" i]','time','a'],compose:['[data-a-target="chat-input"]','textarea[data-a-target*="chat" i]']},
 whatsapp:{roots:['#main','[data-testid="conversation-panel-wrapper"]'],messages:['[data-testid="msg-container"] span.selectable-text','[data-testid="msg-container"] [data-lexical-text="true"]','[data-testid="msg-container"] [data-testid="msg-text"]','.message-in span.selectable-text','.message-out span.selectable-text'],protect:['[data-pre-plain-text]','time','a','button'],compose:['[data-testid="conversation-compose-box-input"]','footer [contenteditable="true"]','[contenteditable="true"][role="textbox"]']},
 telegram:{roots:['#column-center','.chat-container','.chat','.bubbles-inner'],messages:['.bubble:not(.service):not(.is-date) .message','.bubble:not(.service):not(.is-date) .text-content','.message-content','.translatable-message'],protect:['.peer-title','.sender-title','.message-title','.time','time','a','button'],compose:['.input-message-input[contenteditable="true"]','#editable-message-text','[contenteditable="true"][role="textbox"]']},
 discord:{roots:['[data-list-id="chat-messages"]','ol[data-list-id="chat-messages"]','main[aria-label]','main'],messages:['[id^="message-content-"]'],protect:['[id^="message-username-"]','[id^="message-timestamp-"]','[class*="username"]','time','a','button'],compose:['[role="textbox"][data-slate-editor="true"]','[role="textbox"][contenteditable="true"]']},
 gmail:{roots:['div[role="main"]','main'],messages:['.a3s'],protect:['span[email]','[email]','time','a','button'],compose:['div[aria-label="Message Body"]','div[role="textbox"][contenteditable="true"]']},
 custom:{roots:['main','[role="main"]','body'],messages:[],protect:['nav','header','footer','button','a','time','[role="button"]','[contenteditable="true"]'],compose:['textarea','[contenteditable="true"][role="textbox"]']}
};
const qs=(r,s)=>{try{return [...r.querySelectorAll(s)]}catch{return[]}};
const many=(r,a)=>{const z=new Set;for(const s of a||[])qs(r,s).forEach(n=>z.add(n));return[...z]};
function root(p){for(const s of D[p]?.roots||[]){const n=document.querySelector(s);if(n)return n}return null}
function protectedEl(el,p){return(D[p]?.protect||[]).some(s=>{try{return!!el.closest(s)}catch{return false}})}
function explicitMessages(r,p){const set=new Set(many(r,D[p]?.messages));if(p==='twitch'&&!set.size){for(const f of many(r,D[p]?.fragments)){const el=f.closest('[data-a-target="chat-line-message"]')?f.parentElement:f;if(el&&!protectedEl(el,p))set.add(el)}}return[...set].filter(x=>x&&x!==r&&!protectedEl(x,p))}
function fallbackMessages(r,p){const out=new Set(),AR=/[\u0600-\u06FF\u0750-\u077F\u0870-\u089F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/,w=document.createTreeWalker(r,NodeFilter.SHOW_TEXT,{acceptNode(n){const t=(n.nodeValue||'').trim();if(!t||!AR.test(t))return NodeFilter.FILTER_REJECT;const e=n.parentElement;if(!e||e===r||protectedEl(e,p)||e.closest('script,style,button,a,[role="button"]')||e.isContentEditable)return NodeFilter.FILTER_REJECT;const meta=`${e.id||''} ${e.className||''} ${e.getAttribute?.('data-testid')||''}`;if(/user(name)?|author|sender|badge|timestamp|avatar|\btime\b/i.test(meta))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});let n,count=0;while((n=w.nextNode())&&count<500){let el=n.parentElement;if(!el)continue;while(el.parentElement&&el.parentElement!==r&&el.parentElement.childElementCount<=1&&!protectedEl(el.parentElement,p))el=el.parentElement;if(el!==r){out.add(el);count++}}return[...out]}
function messages(r,p){const found=explicitMessages(r,p);return found.length?found:fallbackMessages(r,p)}
E.Detector={platform,defs:D,root,messages,protectedEl,composers:(r,p)=>many(r,D[p]?.compose).filter(x=>!protectedEl(x,p))};
})();
