(async()=>{'use strict';
const E=globalThis.EasyFa,C=E.Config,$=s=>document.querySelector(s);let state=await E.Storage.load(),active=state.active,filter='';
function applyTheme(){document.documentElement.dataset.theme=state.theme==='light'?'light':'dark';const b=$('#themeToggle');if(b){const light=state.theme==='light';b.textContent=light?'🌙 تم تیره':'☀️ تم روشن';b.setAttribute('aria-pressed',String(light))}}
applyTheme();
function customId(){return active.startsWith('custom:')?active.slice(7):null}
function custom(){const id=customId();return id?state.customSites.find(x=>x.id===id):null}
function prof(){return custom()?.profile||state.profiles[active]}
function meta(){const c=custom();return c?{name:c.name||c.host,accent:c.profile.accent}:C.platforms[active]}
async function loadSystemFonts(){if(!chrome.fontSettings?.getFontList)return;try{const list=await new Promise((resolve,reject)=>chrome.fontSettings.getFontList(x=>chrome.runtime.lastError?reject(chrome.runtime.lastError):resolve(x||[])));const known=new Set(C.fonts.map(f=>f.id));for(const item of list){const name=String(item.displayName||item.fontId||'').trim(),id='system:'+encodeURIComponent(String(item.fontId||name));if(!name||known.has(id))continue;C.fonts.push({id,name:`${name} (System)`,family:`"${String(item.fontId||name).replace(/["\\]/g,'\\$&')}"`,system:true,dynamic:true,installed:true});known.add(id)}}catch(e){console.warn('Easy-Fa system font list unavailable',e)}}
async function loadUiFont(){try{const f=await E.FontLoader.faceFor({fontId:'vazirmatn',fontWeight:500,fontSize:16,sizeScope:'all'},16);document.documentElement.style.setProperty('--easyfa-ui-font',`${f.family},Vazirmatn,Tahoma,system-ui,sans-serif`)}catch{document.documentElement.style.setProperty('--easyfa-ui-font','Vazirmatn,Tahoma,system-ui,sans-serif')}}
async function persistActive(){state.active=active;await E.Storage.save(state)}
async function update(patch){const id=customId();if(id){const p=await E.Storage.patchCustom(id,patch);const c=state.customSites.find(x=>x.id===id);if(c)c.profile=p}else state.profiles[active]=await E.Storage.patch(active,patch);render(false);if(Object.prototype.hasOwnProperty.call(patch,'fontId'))await renderFonts()}
function seg(id,val){document.querySelectorAll(`#${id} button`).forEach(b=>b.classList.toggle('active',b.dataset.value===val))}
async function localAvailable(f){if(f.installed||f.dynamic)return true;if(!f.local)return true;try{return document.fonts.check(`16px ${f.family}`)}catch{return false}}
async function renderFonts(){const box=$('#fonts');box.innerHTML='';const p=prof(),q=filter.trim().toLowerCase();let count=0;for(const f of C.fonts){if(q&&!`${f.name} ${f.id}`.toLowerCase().includes(q))continue;const ok=await localAvailable(f),b=document.createElement('button');b.className='font-card'+(p.fontId===f.id?' active':'')+(!ok?' local-missing':'');b.disabled=!ok;b.innerHTML=`<b>${f.name}</b><span>سلام دنیا · Hello 123</span>`;if(ok){try{const face=await E.FontLoader.faceFor({...p,fontId:f.id,sizeScope:'all'},16);b.querySelector('span').style.fontFamily=`${face.family},Tahoma,sans-serif`}catch{}}b.onclick=()=>update({fontId:f.id,enabled:true});box.appendChild(b);count++}$('#fontCount').textContent=`${count} فونت`}
async function preview(){const p=prof();document.documentElement.style.setProperty('--accent',p.accent);for(const id of ['previewFa','previewEn']){const el=$('#'+id),orig='Inter,system-ui,sans-serif';try{const face=await E.FontLoader.faceFor(p,16);el.style.fontFamily=p.fontScope==='fa'?`${face.faFamily},${orig}`:`${face.family},${orig}`}catch{el.style.fontFamily=orig}if(p.sizeScope==='all'){el.style.fontSize=p.fontSize+'px';el.style.fontWeight=p.fontWeight;el.style.lineHeight=p.lineHeight}else{el.style.fontSize='16px';el.style.fontWeight=400;el.style.lineHeight=1.7}if(p.direction==='smart'){el.dir='auto';el.style.direction='';el.style.textAlign='start';el.style.unicodeBidi='plaintext'}else if(p.direction==='site'){el.removeAttribute('dir');el.style.direction='';el.style.textAlign=''}else{el.dir=p.direction;el.style.direction=p.direction;el.style.textAlign=p.direction==='rtl'?'right':'left';el.style.unicodeBidi='isolate'}}}
function renderSites(){const nav=$('#sites');nav.innerHTML='';for(const [id,m] of Object.entries(C.platforms)){const b=document.createElement('button');b.className='site'+(id===active?' active':'');b.textContent=m.name;b.onclick=async()=>{active=id;await persistActive();render()};nav.appendChild(b)}for(const c of state.customSites){const key='custom:'+c.id,b=document.createElement('button');b.className='site custom-site'+(key===active?' active':'');b.textContent=c.name||c.host;b.title=c.host;b.onclick=async()=>{active=key;await persistActive();render()};nav.appendChild(b)}}
function renderCustomList(){const box=$('#customList');box.innerHTML='';for(const c of state.customSites){const row=document.createElement('div');row.className='custom-row';row.innerHTML=`<div><b>${c.name}</b><span>${c.host}</span></div><button type="button">حذف</button>`;row.querySelector('button').onclick=async()=>{const patterns=[`*://${c.host}/*`,`*://*.${c.host}/*`];try{await chrome.permissions.remove({origins:patterns})}catch{}state=await E.Storage.removeCustom(c.id);active=state.active;render()};box.appendChild(row)}if(!state.customSites.length)box.innerHTML='<div class="empty">هنوز سایت اختصاصی اضافه نشده.</div>'}
function renderChatgptOptions(p){const box=$('#chatgptOptions');box.hidden=active!=='chatgpt';if(!box.hidden)$('#chatgptSidebar').checked=p.sidebar!==false}
function renderYoutubeTargets(p){const box=$('#youtubeTargets');box.hidden=active!=='youtube';if(box.hidden)return;box.querySelectorAll('input[data-target]').forEach(i=>{i.checked=p.targets?.[i.dataset.target]!==false})}
function renderCustomAdvanced(p){const box=$('#customAdvanced'),c=custom();box.hidden=!c;if(!c)return;$('#customMode').value=p.customMode||'smart';if(document.activeElement!==$('#customMessageSelector'))$('#customMessageSelector').value=p.messageSelector||'';if(document.activeElement!==$('#customComposerSelector'))$('#customComposerSelector').value=p.composerSelector||''}
function render(full=true){const p=prof(),m=meta();if(!p||!m){active='kick';return render(true)}$('#siteName').textContent=m.name;$('#enabled').checked=p.enabled;seg('applyMode',state.applyMode||'instant');$('#fontSize').value=p.fontSize;$('#fontSizeOut').value=p.fontSize+'px';$('#fontWeight').value=p.fontWeight;$('#lineHeight').value=p.lineHeight;$('#lineHeightOut').value=Number(p.lineHeight).toFixed(2);$('#composer').checked=p.composer;seg('directions',p.direction);seg('fontScope',p.fontScope);seg('sizeScope',p.sizeScope);renderChatgptOptions(p);renderYoutubeTargets(p);renderCustomAdvanced(p);if(full){renderSites();renderFonts();renderCustomList()}preview()}
$('#enabled').onchange=e=>update({enabled:e.target.checked});
$('#fontSize').oninput=e=>update({fontSize:+e.target.value});
$('#fontWeight').onchange=e=>update({fontWeight:+e.target.value});
$('#lineHeight').oninput=e=>update({lineHeight:+e.target.value});
$('#composer').onchange=e=>update({composer:e.target.checked});
$('#chatgptSidebar').onchange=e=>{if(active==='chatgpt')update({sidebar:e.target.checked})};
$('#themeToggle').onclick=async()=>{state.theme=state.theme==='light'?'dark':'light';await E.Storage.save(state);applyTheme()};
$('#applyMode').onclick=async e=>{const b=e.target.closest('button');if(!b)return;state.applyMode=b.dataset.value==='delayed'?'delayed':'instant';await E.Storage.save(state);seg('applyMode',state.applyMode)};
for(const id of ['directions','fontScope','sizeScope'])$('#'+id).onclick=e=>{const b=e.target.closest('button');if(!b)return;update({[id==='directions'?'direction':id]:b.dataset.value})};
$('#fontSearch').oninput=e=>{filter=e.target.value;renderFonts()};
$('#youtubeTargets').onchange=e=>{const i=e.target.closest('input[data-target]');if(!i||active!=='youtube')return;const p=prof(),targets={...(p.targets||C.youtubeTargets()),[i.dataset.target]:i.checked};update({targets})};
$('#customMode').onchange=e=>{if(customId())update({customMode:e.target.value})};
async function saveCustomSelector(input,key){if(!customId())return;const value=input.value.trim();try{if(value)document.querySelector(value)}catch{return alert('Selector معتبر نیست. لطفاً CSS selector درست وارد کن.')}await update({[key]:value})}
for(const [id,key] of [['customMessageSelector','messageSelector'],['customComposerSelector','composerSelector']]){const input=$('#'+id);input.addEventListener('change',()=>saveCustomSelector(input,key));input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();input.blur()}})}
$('#addCustom').onclick=async()=>{const host=E.Storage.cleanHost($('#customHost').value),name=$('#customName').value.trim();if(!host||!host.includes('.'))return alert('دامنه معتبر وارد کن؛ مثلا example.com');const origins=[`*://${host}/*`,`*://*.${host}/*`];let granted=false;try{granted=await chrome.permissions.request({origins})}catch{}if(!granted)return alert('برای فعال شدن سایت اختصاصی باید دسترسی همان دامنه را تأیید کنی.');const item=await E.Storage.addCustom({host,name});state=await E.Storage.load();active='custom:'+item.id;$('#customHost').value='';$('#customName').value='';render()};
await Promise.allSettled([loadSystemFonts(),loadUiFont()]);render();})();
